version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - "./frontend:/noc"
      - "/noc/node_modules"
    ports:
      - "8080:3000"
  server:
    build:
      context: ./server
      dockerfile: ../server.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - "./server:/noc_server"
      - "/noc_server/node_modules"
    ports:
      - "9090:9090"
