version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - "./frontend:/noc"
      - "/noc/node_modules"
    ports:
      - "8080:3000"
